server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-server-service
  cloud:
    stream:
      bindings:
        output:
          destination: app-events-output
        input:
          destination: todo-events-output
      # rabbit: bindings: input: consumer: exchange-type: direct

management:
  endpoints:
    web:
      exposure:
        include: '*'